### ISSUE TITLE
Support Cython v3

### ISSUE THREAD

**Issue by bjlittle** [ocefpaf/cf_units#360]
( was formerly : "**drop cython language_level on v3.0.0**" )

## 📰 Custom Issue

Once `cython` 3.0.0 lands:

- drop use of the `cython` `language_level` compiler directive (`3str` will be the default behaviour)
  - #358
- add a min pin for `cython>=3.0` for `conda` and PyPI deps
- address `warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]`, see
  - https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html?highlight=NPY_NO_DEPRECATED_API#numpy-c-api 
  - https://cython.readthedocs.io/en/latest/src/tutorial/numpy.html?highlight=import_array#adding-types

See https://github.com/cython/cython/milestone/58

**Comment by pp-mo** [comment]
For avoidance of doubt, the cython 3.0 milestone (linked above) was closed Nov 2023 (!!)

**Comment by trexfeathers** [comment]
Currently struggling to get a current example of the `NPY_1_7_API_VERSION` warning - so that I can confirm I have successfully suppressed it! Due to log retention we no longer have any successful GHA examples, and when I build locally I don't get the warning.

Hoping #455 will produce what I need.

It did occur to me that NumPy might have removed the warning now that Cython has been around for a few months, but I cannot find any evidence of this:

- https://github.com/search?q=repo%3Anumpy%2Fnumpy+NPY_1_7_API_VERSION&type=pullrequests
- https://github.com/search?q=repo%3Anumpy%2Fnumpy+NPY_1_7_API_VERSION&type=issues

**Comment by pp-mo** [comment]
Closed by #460
