### ISSUE TITLE
`cf_units.Unit.is_time` does not work for time units with format `<time units> since <reference time>`

### ISSUE THREAD

**Issue by SeanBryan51** [ocefpaf/cf_units#474]
## 🐛 Bug Report

The `cf_units.Unit.is_time` method returns `False` for units with the format `<time units> since <reference time>` when it should return `True`.

## How to Reproduce

Run the following command in the python interpreter:

```
$ python -c 'import cf_units; u = cf_units.Unit("days since 1990-1-1 0:0:0"); print(u.is_time())'
False
```

## Expected Behaviour

The command should output `True`:

```
$ python -c 'import cf_units; u = cf_units.Unit("days since 1990-1-1 0:0:0"); print(u.is_time())'
True
```

## Environment 
 - OS & Version: `Rocky Linux 8.10`
 - cf-units Version: `3.2.0`

**Comment by rcomer** [comment]
I think this is the expected behaviour.  This method returns `True` for units such as seconds, days, years (without the reference).  We also have the [is_time_reference](https://cf-units.readthedocs.io/en/latest/unit.html#cf_units.Unit.is_time_reference) method which is likely more suitable for your use case.

**Comment by SeanBryan51** [comment]
Thanks @rcomer - my apologies for not noticing that method sooner. Closing this issue.
